[project]
name = 'Solar-System-Communication-Grid'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.interplanetary-relay-network]
path = 'contracts/interplanetary-relay-network.clar'
clarity_version = 3
epoch = '3.2'

[contracts.signal-analysis-engine]
path = 'contracts/signal-analysis-engine.clar'
clarity_version = 3
epoch = '3.2'

[contracts.space-exploration-rewards]
path = 'contracts/space-exploration-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.space-mission-coordinator]
path = 'contracts/space-mission-coordinator.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
